### ISSUE TITLE
Import resources from OPC

### ISSUE THREAD

**Issue by carlomarini** [terraform-providers/terraform-provider-opc#47]
Hi,
# question 1
Is there a way to import OPC resources (example Instances, Storage, etc) with terraform ? Of course resources that has not been created by Terraform.

# question 2
is it possible to use JSON file of OPC orchestration as Terraform input to create resources? This would be a workaround for quetsion 1

Thanks
Carlo

**Comment by grubernaut** [comment]
Hi @carlomarini, thanks for the issue!

> Question 1
Yes, it is possible to import OPC resources with Terraform. 
See the following documentation pages for more: 
 - https://www.terraform.io/docs/commands/import.html
 - https://www.terraform.io/docs/import/index.html
 - https://www.terraform.io/docs/import/importability.html#opc-oracle-public-cloud-
Each resource in the OPC docs should also have an `#Import` section if that resource can be imported, along with an example import statement that can be used to import the resource into Terraform. 

> Question 2
No, it is currently not possible to use the JSON file for an OPC Orchestration as input to Terraform. You can, however, write your Terraform configuration as JSON, but we don't have any plans to support using the JSON from an Orchestration to create resources in OPC. We do plan on adding an orchestration resource, where that might be possible, but it will still need to be written using Terraform's syntax. 

Hope this helps, thanks!

**Comment by carlomarini** [comment]
Thanks a lot!
Actually I did try to import from OPC but according to my test the import works only if the OPC resources has been created by Terraform. Is it correct?

Thanks a lot Carlo

**Comment by grubernaut** [comment]
Hi @carlomarini, 

You should be able to import resources into a Terraform Statefile if the resource was previously created manually. 
For example, I can create an OPC instance using Oracle's Web UI, then import the instance into a Terraform Statefile by using the following: 
```
terraform import opc_instance.foo instance_name/instance_id
```

With recent changes to Terraform, however, it's necessary to add the proper configuration for the resource so Terraform knows which provider to load during `import` time, but adding the configuration for the resource without running `plan` or `apply` doesn't create a resource. 

Thus, in order to import the instance from above, I would simply need to add the following piece of config to my Terraform config, but don't need to run `plan` or `apply`. 

```
resource "opc_compute_instance" "foo" {
  # resource to be imported
}
```

Once the resource is imported into my statefile, I can then run `terraform plan` to see what needs to be updated inside my configuration stub above, so I end up with an empty plan. 

Hope this helps! If you have any more questions, feel free to reach out. Thanks
